build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script: dotnet pack --output . -p:PackageVersion=0.9.$CI_PIPELINE_IID
  artifacts:
    paths:
      - '*.nupkg'

deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  only: [master]
  script:
    for package in *.nupkg;
    do
      dotnet nuget push "$package" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY;
    done
